# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:   Rogue Financial
tagline: Tech
email:   tech@roguefinancial.com
description: >
  Rogue Financial Tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.rogue.tech" # the base hostname & protocol for your site
twitter_username: RogueFinancial
twitter:
  username: RogueFinancial
github_username:  RogueFinancial
paginate: 5
author:
  name:    Rogue Financial
  twitter: https://twitter.com/RogueFinancial
  github:  https://github.com/RogueFinancial
permalink: pretty

# Tags
tag_page_layout: tag_page
tag_page_dir:    tag

# Custom vars
version: 1.0.0

# Build settings
highlighter: rouge
markdown: redcarpet
gems:
  - jekyll-angular
  - jekyll-compose
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll/tagging

# Exclusions
exclude:
  - util/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
